import { downloadReservationForm } from './reservation-form'
import CollegeText from './CollegeText'
import { useEffect, useState } from 'react'
import './App.css'
import './StudentSite.css'
import college from './college-content.json'
import AdminPortal from './AdminPortal'
import BookingForm from './BookingForm'
import { requestJson, API_CONFIGURED } from './api'
import previewFacilities from './facility-preview.json'
import SpaceIllustration from './SpaceIllustration'

const userNavigation=[['Dashboard','Home'],['Facilities','Explore spaces'],['Reservations','My bookings'],['Facility Schedule','Availability'],['About CeC','About CeC'],['Laboratory Guidelines','Help & guidelines']]
const helpPages=['Laboratory Guidelines','Damage & Loss Reports','Laboratory Utilization','Contact']
const dateLabel=value=>new Date(value+'T00:00:00').toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'})
const statusLabel=value=>value==='Awaiting signature'?'Waiting for approval':value==='Rejected'?'Request declined':value
const earliestBooking = () => { const date = new Date(today()+'T00:00:00Z'); date.setUTCDate(date.getUTCDate()+2); return date.toISOString().slice(0,10) }
const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila'}).format(new Date())
function userSession(){let token=localStorage.getItem('hm-user-session');if(!token){token=crypto.randomUUID();localStorage.setItem('hm-user-session',token)}return token}
async function api(path, options) { return requestJson('/api/'+path,{...options,headers:{'Content-Type':'application/json','X-User-Session':userSession()}}) }
export default function App(){return window.location.pathname.startsWith('/admin')?<AdminPortal/>:<UserPortal/>}
function UserPortal(){
 const [facilities,setFacilities]=useState(previewFacilities.map(f=>[f.name,f.category,'',f.description])),[facilityInfo,setFacilityInfo]=useState(previewFacilities)
 const [loading,setLoading]=useState(API_CONFIGURED),[bookingView,setBookingView]=useState('All')
 const [schedule,setSchedule]=useState([]),[menuOpen,setMenuOpen]=useState(false),[scheduleFacility,setScheduleFacility]=useState('All spaces'),[scheduleDate,setScheduleDate]=useState('')
 const [page,setPage]=useState('Dashboard'),[category,setCategory]=useState('All facilities'),[search,setSearch]=useState(''),[data,setData]=useState({reservations:[],reports:[],utilization:[]}),[modal,setModal]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function refresh(){if(!API_CONFIGURED)return;setLoading(true);try{const [records,slots,spaces]=await Promise.all([api('records'),api('schedule'),api('facilities').then(spaces=>{setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]));return spaces})]);setData(records);setSchedule(slots);setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]));setError('')}catch{setError('Reservation service unavailable. Please check that the server is running.')}finally{setLoading(false)}}
 useEffect(()=>{if(!API_CONFIGURED)return;let alive=true;Promise.all([api('records'),api('schedule'),api('facilities').then(spaces=>{setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]));return spaces})]).then(([records,slots,spaces])=>{if(alive){setData(records);setSchedule(slots);setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]))}}).catch(()=>{if(alive)setError('Reservation service unavailable. Please check that the server is running.')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[])
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector('.student-site .modal');const close=e=>{if(e.key==='Escape'&&!busy)setModal(null);if(e.key==='Tab'){const controls=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],summary')].filter(el=>el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=overflow;if(!document.querySelector('.student-site .modal'))previous?.focus()}},[modal,busy])

 useEffect(()=>{if(!API_CONFIGURED)return;let running=false;const sync=async()=>{if(document.hidden||running)return;running=true;try{const [records,slots,spaces]=await Promise.all([api('records'),api('schedule'),api('facilities').then(spaces=>{setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]));return spaces})]);setData(records);setSchedule(slots);setFacilityInfo(spaces);setFacilities(spaces.map(f=>[f.name,f.category,'',f.description]))}catch{/* Keep the last working view until a manual retry. */}finally{running=false}};const timer=setInterval(sync,30000);window.addEventListener('focus',sync);return()=>{clearInterval(timer);window.removeEventListener('focus',sync)}},[])
 function navigate(destination){setPage(destination);setMenuOpen(false);setNotice('');window.scrollTo({top:0,behavior:'smooth'})}
 function open(kind,facility=''){if(!API_CONFIGURED){setNotice('Online booking is not connected yet. Please contact the HM laboratory office for assistance.');return}setMenuOpen(false);setNotice('');setModal({kind,facility});if(kind==='reservations')refresh()}
 async function saveRecord(fields){setBusy(true);setNotice('');try{const saved=await api(modal.kind,{method:'POST',body:JSON.stringify(fields)});await refresh();setPage(modal.kind==='reservations'?'Reservations':modal.kind==='reports'?'Damage & Loss Reports':'Laboratory Utilization');setModal(null);setNotice(modal.kind==='reservations'?'Your booking request has been sent. Your filled form is ready. Print it and arrange the instructor signature while you wait for approval.':modal.kind==='reports'?'Your concern has been sent to the laboratory office. You can check for a response here.':'Your laboratory visit has been saved.');window.scrollTo({top:0,behavior:'smooth'});if(modal.kind==='reservations'){try{await downloadReservationForm(saved)}catch(e){setNotice(e.message)}}}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 function submit(e){e.preventDefault();saveRecord(Object.fromEntries(new FormData(e.currentTarget)))}

 async function cancel(){setBusy(true);try{await api('reservations/'+modal.facility,{method:'DELETE'});await refresh();setModal(null);setNotice('Reservation cancelled.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const upcoming=data.reservations.filter(r=>!['Cancelled','Rejected'].includes(r.status)&&r.date>=today()).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))
 const filteredBookings=data.reservations.filter(r=>bookingView==='All'||(bookingView==='Upcoming'?r.date>=today()&&!['Rejected','Cancelled'].includes(r.status):bookingView==='Waiting for approval'?r.status==='Awaiting signature':r.date<today()||['Rejected','Cancelled'].includes(r.status)))
 const visible=facilities.filter(f=>(category==='All facilities'||f[1]===category)&&f.join(' ').toLowerCase().includes(search.toLowerCase()))
 return <div className="student-site"><div className="college-strip"><span><CollegeText>Cristal e-College</CollegeText> · Hospitality Management</span><span>Tawala, Panglao, Bohol</span></div><header className="student-header"><a className="brand" href="#home" onClick={e=>{e.preventDefault();navigate('Dashboard')}}><img src="/cec.png" alt="Cristal e-College seal"/><span>CRISTAL <b className="college-red-e">e</b>-COLLEGE<small>HM SPACES & RESERVATIONS</small></span></a><button className="mobile-menu" aria-expanded={menuOpen} aria-controls="student-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?'Close ✕':'Menu ☰'}</button><nav id="student-navigation" className={menuOpen?'is-open':''} aria-label="Main navigation">{userNavigation.map(([destination,label])=><button key={destination} className={page===destination||(destination==='Laboratory Guidelines'&&helpPages.includes(page))?'active':''} aria-current={page===destination?'page':undefined} onClick={()=>navigate(destination)}>{label}</button>)}</nav><button className="primary header-book" onClick={()=>open('reservations')}>Book a space ↗</button></header><a className="skip-content" href="#main-content">Skip to content</a><main className="student-main" id="main-content">{!API_CONFIGURED&&<div className="deployment-notice" role="status">Online booking is coming soon. You can explore our spaces and guidelines while the booking service is being connected.</div>}{page!=='Dashboard'&&<div className="student-page-heading"><div className="eyebrow"><CollegeText>CRISTAL e-COLLEGE</CollegeText> HM SPACES</div><h1>{page==='Facilities'?'A space for every experience.':page==='Reservations'?'My bookings':page==='Facility Schedule'?'Plan your visit':page==='Laboratory Guidelines'?'A little preparation goes a long way.':page==='Damage & Loss Reports'?'Report a concern':page==='Laboratory Utilization'?'Record your laboratory visit':page==='Contact'?'Let’s help you get started.':page}</h1><p>{page==='Facilities'?'From your first culinary practice to your next campus event, find the right place to begin.':page==='Reservations'?'Check your booking progress and details, all in one place.':page==='Facility Schedule'?'Check occupied times before choosing a date for your activity.':helpPages.includes(page)?'Everything you need before, during, and after using our spaces.':'Knowledge, leadership, and humanity.'}</p></div>}{error&&<div className="alert" role="alert">We couldn’t load bookings right now. Please try again. <button onClick={refresh}>Try again</button></div>}{notice&&!modal&&<div className="notice" role="status">{notice}</div>}{helpPages.includes(page)&&<div className="help-navigation" aria-label="Help topics">{helpPages.map((destination,i)=><button className={page===destination?'active':''} key={destination} onClick={()=>navigate(destination)}>{['Using our spaces','Report a concern','Record a visit','Contact us'][i]}</button>)}</div>}
 {page==='Dashboard'&&<><div className="browse-intro"><div><div className="eyebrow">HM LABORATORY RESERVATIONS</div><h1>Find the right space for your activity.</h1><p>Explore our campus facilities, choose a time, and send your request.</p></div><button className="availability-link" onClick={()=>navigate('Facility Schedule')}>◷ Check occupied times <span>→</span></button></div><section className="booking-steps" aria-label="How to reserve"><div><span>01</span><div><h3>Choose your space</h3><p>Find a facility that fits your activity.</p></div></div><div><span>02</span><div><h3>Send your request</h3><p>Add your date, time, and activity details.</p></div></div><div><span>03</span><div><h3>Get ready for your visit</h3><p>Complete the form and wait for approval.</p></div></div></section></>}
 {['Dashboard','Facilities'].includes(page)&&<section><div className="section-heading"><div><div className="eyebrow">SPACES TO EXPLORE</div><h2>Explore our spaces</h2><p>Choose a facility that fits your class, practice, or gathering.</p></div><input className="search" aria-label="Search facilities" placeholder="⌕  Search facilities…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{['All facilities',...new Set(facilities.map(f=>f[1]))].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="browse-results"><span>{visible.length} {visible.length===1?'space':'spaces'}{category!=='All facilities'?' in '+category:' to explore'}</span>{(search||category!=='All facilities')&&<button onClick={()=>{setSearch('');setCategory('All facilities')}}>Clear filters ×</button>}<span>Request at least 2 days ahead</span></div><div className="facility-grid">{visible.map(f=><article className="facility-card" key={f[0]}><div className={'facility-art art-'+facilities.indexOf(f)%5+(facilityInfo.find(room=>room.name===f[0])?.photo?' has-photo':'')}>{facilityInfo.find(room=>room.name===f[0])?.photo?<img className="facility-photo" src={facilityInfo.find(room=>room.name===f[0]).photo} alt={f[0]} loading="lazy"/>:<SpaceIllustration category={f[1]}/>}<small>HM / {String(facilities.indexOf(f)+1).padStart(2,'0')}</small></div><div className="facility-content"><div className="card-meta">{f[1]}<span className={facilityInfo.find(room=>room.name===f[0])?.status==='Unavailable'?'unavailable-label':''}>{facilityInfo.find(room=>room.name===f[0])?.status==='Unavailable'?'Temporarily unavailable':'Open for requests'}</span></div><h3>{f[0]}</h3><p>{f[3]}</p><button disabled={facilityInfo.find(room=>room.name===f[0])?.status==='Unavailable'} onClick={()=>open('reservations',f[0])}>{facilityInfo.find(room=>room.name===f[0])?.status==='Unavailable'?'Currently unavailable':'Request this space'} <span>↗</span></button>{facilityInfo.find(room=>room.name===f[0])?.status==='Unavailable'&&<small className="facility-closure-note">{facilityInfo.find(room=>room.name===f[0])?.reason}</small>}</div></article>)}</div>{!visible.length&&<div className="empty">{loading?'Loading facilities…':'No spaces match your search. Try another name or category.'}</div>}</section>}
 {page==='Reservations'&&<section className="my-bookings"><div className="booking-toolbar"><span>{upcoming.length} upcoming {upcoming.length===1?'booking':'bookings'}</span><div><button className="hero-link" disabled={loading} onClick={refresh}>{loading?'Refreshing…':'Refresh updates ↻'}</button><button className="primary" onClick={()=>navigate('Facilities')}>Find a space ↗</button></div></div><p className="device-note">Bookings made in this browser appear here.</p><div className="booking-view-filters">{['All','Upcoming','Waiting for approval','Past / closed'].map(view=><button key={view} aria-pressed={bookingView===view} className={bookingView===view?'active':''} onClick={()=>setBookingView(view)}>{view}</button>)}</div>{loading&&<p className="loading-status" role="status">Loading your latest bookings…</p>}<div className="booking-card-grid">{[...filteredBookings].reverse().map(r=><article className="personal-booking" key={r.id}><div className="personal-booking-top"><span className={'booking-status status-'+r.status.replaceAll(' ','-')}>{statusLabel(r.status)}</span><span className="booking-date">{dateLabel(r.date)}</span></div><h2>{r.facility}</h2><button className="secondary" onClick={()=>downloadReservationForm(r).catch(e=>setNotice(e.message))}>Download filled form ↓</button><p className="booking-time">◷ {r.start} – {r.end}</p><p>{r.purpose}</p><details><summary>View booking details</summary><dl><dt>Requested by</dt><dd>{r.name}</dd>{r.email&&<><dt>Email address</dt><dd>{r.email}</dd></>}{r.studentId&&<><dt>ID number</dt><dd>{r.studentId}</dd></>}<dt>Subject / activity</dt><dd>{r.subject}</dd><dt>College contact</dt><dd>{r.instructor}</dd><dt>Equipment</dt><dd>{r.equipment}</dd></dl></details>{r.reviewNote&&<div className="booking-feedback"><strong>A note from the laboratory office</strong><p>{r.reviewNote}</p></div>}{r.status==='Awaiting signature'&&<div className="booking-next-step">Next: complete the utilization form and have your instructor sign it.<a href={college.labFormUrl} download>Download form ↓</a></div>}{!['Cancelled','Rejected'].includes(r.status)&&<button className="cancel-booking" onClick={()=>open('cancel',r.id)}>Cancel this booking</button>}</article>)}</div>{!loading&&data.reservations.length>0&&!filteredBookings.length&&<div className="friendly-empty"><h2>No bookings in this view.</h2><p>Try another filter to find your request.</p><button className="secondary" onClick={()=>setBookingView('All')}>Show all bookings</button></div>}{!loading&&!data.reservations.length&&<div className="friendly-empty"><span>✧</span><h2>Your next experience starts here.</h2><p>You haven’t requested a space yet. Browse our facilities and find one for your activity.</p><button className="primary" onClick={()=>navigate('Facilities')}>Explore spaces ↗</button></div>}</section>}
 {['Laboratory Utilization','Damage & Loss Reports'].includes(page)&&<section className="records"><div className="section-heading"><p>{page==='Laboratory Utilization'?'Finished your laboratory activity? Add the details of your visit.':'Found a damaged or missing item? Let the laboratory office know.'}</p><button className="primary" onClick={()=>open(page==='Laboratory Utilization'?'utilization':'reports')}>{page==='Laboratory Utilization'?'＋ Record a visit':'＋ Report a concern'}</button></div>{(page==='Laboratory Utilization'?data.utilization:data.reports).map(r=><article className="record" key={r.id}><span className="badge">{r.type?(r.type+' · '+(r.status||'Open')):'Completed session'}</span><h3>{r.facility}</h3><p>{r.details||r.purpose}</p>{r.resolution&&<p><strong>Resolution:</strong> {r.resolution}</p>}<small>{r.name} · {r.date}{r.start&&` · ${r.start}–${r.end} · ${r.attendees} participants`}</small></article>)}{!(page==='Laboratory Utilization'?data.utilization:data.reports).length&&<div className="empty">Nothing here yet. Your submitted visits or reports will appear here.</div>}</section>}
 {page==='Facility Schedule'&&<section className="visitor-schedule"><div className="schedule-controls"><label>Choose a space<select value={scheduleFacility} onChange={e=>setScheduleFacility(e.target.value)}><option>All spaces</option>{facilities.map(f=><option key={f[0]}>{f[0]}</option>)}</select></label><label>Choose a date<input type="date" value={scheduleDate} min={today()} onChange={e=>setScheduleDate(e.target.value)}/></label><button className="hero-link" onClick={()=>{setScheduleDate('');setScheduleFacility('All spaces')}}>Clear filters</button></div><p className="schedule-note">These times are occupied. Choose another time for your request; availability is checked again when you submit.</p><div className="occupied-times">{schedule.filter(r=>r.date>=today()&&(scheduleFacility==='All spaces'||r.facility===scheduleFacility)&&(!scheduleDate||r.date===scheduleDate)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(r=><article key={r.id}><span>◷</span><div><h3>{r.facility}</h3><p>{dateLabel(r.date)} · {r.start} – {r.end}</p></div><small>Occupied</small></article>)}</div>{!schedule.some(r=>r.date>=today()&&(scheduleFacility==='All spaces'||r.facility===scheduleFacility)&&(!scheduleDate||r.date===scheduleDate))&&<div className="friendly-empty"><span>☀</span><h2>No occupied times listed.</h2><p>Choose your preferred date and time in the booking form.</p></div>}<button className="primary" onClick={()=>open('reservations',scheduleFacility==='All spaces'?'':scheduleFacility)}>Request a space ↗</button></section>}
 {page==='Laboratory Guidelines'&&<section className="guidelines"><span className="badge">HRM Laboratory Utilization Form</span><h2>Laboratory reservation and equipment guidelines</h2><p>Follow these requirements when requesting and using the HM laboratory.</p>{college.rules.map((text,i)=><article key={text}><span>0{i+1}</span><div><h3>{['Reserve in advance','Complete the request','Instructor signature','Return borrowed equipment','Multi-day inventory','Damage or loss'][i]}</h3><p><CollegeText>{text}</CollegeText></p></div></article>)}<a className="document-link" href={college.labFormUrl} download>Download laboratory utilization form ↓</a></section>}
 {page==='About CeC'&&<section className="about-college"><div className="college-intro"><img src="/cec.png" alt="Cristal e-College seal"/><div><div className="eyebrow">KNOWLEDGE · LEADERSHIP · HUMANITY</div><h2>About <CollegeText>Cristal e-College</CollegeText></h2><p>Tawala, Panglao, Bohol 6340 Philippines</p></div></div><div className="college-sections">{college.sections.map(section=><article className="college-section" key={section.title}><h2><CollegeText>{section.title}</CollegeText></h2>{section.paragraphs?.map(text=><p key={text}><CollegeText>{text}</CollegeText></p>)}{section.items&&<ul className={section.title==='Core Values'?'values-list':''}>{section.items.map(text=><li key={text}><CollegeText>{text}</CollegeText></li>)}</ul>}{section.note&&<small><CollegeText>{section.note}</CollegeText></small>}</article>)}</div><section className="college-section"><h2>College organization</h2><p className="source-note">As listed in the supplied About CeC document.</p>{college.organization.map(group=><details key={group.title}><summary>{group.title}</summary><ul>{group.items.map(text=><li key={text}><CollegeText>{text}</CollegeText></li>)}</ul></details>)}</section><section className="college-section"><h2>College documents</h2><div className="document-list">{college.downloads.map(doc=><a key={doc.url} href={doc.url} download>{doc.name.startsWith('ACA-')?'HRM Laboratory Utilization Form':doc.name.replace('.docx','')} <span>Word document ↓</span></a>)}</div></section></section>}
 {page==='Contact'&&<section className="contact-panel"><img src="/cec.png" alt="Cristal e-College"/><div className="eyebrow">WE’RE HERE TO HELP</div><h2>HM Laboratory Office</h2><p><CollegeText>Cristal e-College</CollegeText><br/>Tawala, Panglao, Bohol 6340 Philippines</p><p><strong>Laboratory In-Charge</strong><br/>Cristian Jay M. Pechon<br/><small>Listed on the supplied laboratory utilization form.</small></p><p>For booking approval, equipment concerns, or laboratory assistance, contact your HM instructor or laboratory coordinator in person.</p><small>Official contact details can be added by the department.</small></section>}
 {page==='Dashboard'&&<section className="student-help-banner"><div><div className="eyebrow">BEFORE YOU VISIT</div><h2>A great experience starts with a little preparation.</h2><p>Find the reservation guidelines, required form, and help from the laboratory office.</p></div><button className="secondary" onClick={()=>navigate('Laboratory Guidelines')}>Read the guidelines →</button></section>}</main><footer className="student-footer"><div><strong><CollegeText>CRISTAL e-COLLEGE</CollegeText></strong><p>Excellence in Global Education<br/>Tawala, Panglao, Bohol 6340 Philippines</p></div><div className="footer-links"><button onClick={()=>navigate('Facility Schedule')}>Check schedules</button><button onClick={()=>navigate('Contact')}>Contact us</button><a href="/admin">Staff sign in</a></div><small>© {new Date().getFullYear()} <CollegeText>Cristal e-College</CollegeText> · Hospitality Management</small></footer>
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="close" aria-label="Close dialog" disabled={busy} onClick={()=>setModal(null)}>×</button><div className="eyebrow">YOUR NEXT CAMPUS EXPERIENCE</div><h2 id="dialog-title">{modal.kind==="cancel"?"Cancel reservation?":modal.kind==="reservations"?"Request your space":modal.kind==="reports"?"Tell us what happened":"Record your visit"}</h2>{modal.kind==='cancel'?<><p>This will release the reserved time.</p><div className="cancel-actions"><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>Keep my booking</button><button className="primary" disabled={busy} onClick={cancel}>{busy?'Cancelling…':'Cancel booking'}</button></div></>:modal.kind==='reservations'?<BookingForm facilityInfo={facilityInfo} facilities={facilities} facility={modal.facility} date={scheduleDate} minDate={earliestBooking()} schedule={schedule} busy={busy} onSubmit={saveRecord}/>:<form onSubmit={submit}><label>Facility<select name="facility" required defaultValue={modal.facility} autoFocus><option value="">Choose a facility</option>{facilities.map(f=><option key={f[0]}>{f[0]}</option>)}</select></label><div className="form-row"><label>Full name<input name="name" required maxLength={100} autoComplete="name"/></label><label>ID number (optional)<input name="studentId" maxLength={40} placeholder="Leave blank if you do not have an ID"/></label></div><label>Email address<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.com"/></label><label>Date<input type="date" name="date" required defaultValue={today()} max={modal.kind==='utilization'?today():undefined}/></label>{modal.kind==='utilization'?<><div className="form-row"><label>Start time<input name="start" type="time" required/></label><label>End time<input name="end" type="time" required/></label></div><label>Purpose / activity<textarea name="purpose" required maxLength={1000}/></label><label>Participants<input name="attendees" type="number" min="1" max="500" required/></label></>:<><label>Report type<select name="type"><option>Damage</option><option>Loss</option></select></label><label>Item and incident details<textarea name="details" required maxLength={2000}/></label></>}<button className="primary submit" disabled={busy}>{busy?'Sending…':modal.kind==='reports'?'Send report':'Save visit'}</button></form>}{notice&&<div className="alert" role="alert">{notice}</div>}</section></div>}</div>
}



