import {useState} from 'react'
import college from './college-content.json'
export default function BookingForm({facilities,facilityInfo,facility,date,minDate,schedule,busy,onSubmit}){
 const [step,setStep]=useState(0),[fields,setFields]=useState({facility:facility||'',date:date>=minDate?date:minDate,start:'',end:'',name:'',email:'',studentId:'',subject:'',instructor:'',purpose:'',equipment:'None',termsAccepted:false}),[problem,setProblem]=useState('')
 const [items,setItems]=useState([])
 const updateItem=(index,key,value)=>{const next=items.map((item,i)=>i===index?{...item,[key]:value}:item);setItems(next);setFields({...fields,equipment:next.length?next.map(item=>item.quantity+' | '+item.description).join('\n'):'None'})}
 const changeItems=next=>{setItems(next);setFields({...fields,equipment:next.length?next.map(item=>item.quantity+' | '+item.description).join('\n'):'None'})}
 const update=e=>{const {name,value,type,checked}=e.target;setFields({...fields,[name]:type==='checkbox'?checked:value});setProblem('')}
 const occupied=schedule.filter(r=>r.facility===fields.facility&&r.date===fields.date)
 function next(e){e.preventDefault();setProblem('');if(step===0){if(facilityInfo?.find(room=>room.name===fields.facility)?.status==='Unavailable'){setProblem('This space is currently unavailable. Please choose another facility.');return}if(fields.end<=fields.start){setProblem('Choose an end time after your start time.');return}if(occupied.some(r=>r.start<fields.end&&r.end>fields.start)){setProblem('That time overlaps an existing booking. Choose another time.');return}}if(step<2)setStep(step+1);else onSubmit(fields)}
 return <form className="guided-booking" onSubmit={next}><ol className="booking-progress" aria-label="Booking progress">{['Space & time','Your details','Review & send'].map((label,i)=><li key={label} className={step===i?'current':step>i?'complete':''} aria-current={step===i?'step':undefined}><span>{step>i?'✓':i+1}</span>{label}</li>)}</ol>
 {step===0&&<div className="booking-step-content"><h3>Where and when?</h3><p className="step-description">Choose your space and a time for your activity.</p><label>Space<select name="facility" value={fields.facility} onChange={update} required autoFocus><option value="">Choose a space</option>{facilities.map(f=><option key={f[0]} disabled={facilityInfo?.find(room=>room.name===f[0])?.status==='Unavailable'}>{f[0]}{facilityInfo?.find(room=>room.name===f[0])?.status==='Unavailable'?' (unavailable)':''}</option>)}</select></label><label>Date<input type="date" name="date" min={minDate} required value={fields.date} onChange={update}/><small className="field-hint">Book at least 2 days ahead. All times are Philippine time.</small></label><div className="form-row"><label>Start time<input name="start" type="time" value={fields.start} onChange={update} required/></label><label>End time<input name="end" type="time" value={fields.end} onChange={update} required/></label></div>{fields.facility&&<div className="time-guidance"><strong>{occupied.length?'Already occupied on this date':'No occupied times listed for this date'}</strong>{occupied.length?<ul>{occupied.map(r=><li key={r.id}>{r.start} – {r.end}</li>)}</ul>:<p>Choose your preferred time. We’ll check it again when you send your request.</p>}</div>}</div>}
 {step===1&&<div className="booking-step-content"><h3>Let’s get to know you.</h3><p className="step-description">Your email helps the laboratory office reach you about this request.</p><label>Full name<input name="name" value={fields.name} onChange={update} required maxLength={100} autoComplete="name" autoFocus placeholder="Your full name"/></label><label>Email address<input name="email" type="email" value={fields.email} onChange={update} required maxLength={254} autoComplete="email" placeholder="you@example.com"/></label><label>ID number <span className="optional-label">Optional</span><input name="studentId" value={fields.studentId} onChange={update} maxLength={40} placeholder="ID number, if you are a student or faculty"/></label><div className="contact-note">Students, faculty, and visitors can request a space. Your ID number is optional.</div></div>}
 {step===2&&<div className="booking-step-content"><h3>A few details about your activity.</h3><p className="step-description">Check your plan and complete the activity details before sending.</p><div className="request-summary"><strong>{fields.facility}</strong><p>{new Date(fields.date+'T00:00:00').toLocaleDateString('en-PH',{month:'long',day:'numeric',year:'numeric'})} · {fields.start} – {fields.end}</p><small>{fields.name} · {fields.email}</small><button type="button" onClick={()=>setStep(0)}>Edit schedule</button></div><div className="form-row"><label>Subject / event<input name="subject" required maxLength={80} value={fields.subject} onChange={update} autoFocus placeholder="e.g. Culinary Arts practical"/></label><label>Instructor / college contact<input name="instructor" required maxLength={80} value={fields.instructor} onChange={update} placeholder="Contact person’s full name"/></label></div><label>Purpose / activity<textarea name="purpose" required maxLength={300} value={fields.purpose} onChange={update} placeholder="Briefly describe the activity for the printed form."/></label><fieldset className="equipment-fields"><legend>Items / equipment</legend><p className="field-hint">Add one item per row, as it will appear in the college form. Leave this empty if no equipment is needed.</p>{items.map((item,i)=><div className="equipment-entry" key={i}><label>Quantity<input type="number" min="1" max="9999" step="1" required value={item.quantity} onChange={e=>updateItem(i,'quantity',e.target.value)}/></label><label>Item description<input required maxLength={80} value={item.description} onChange={e=>updateItem(i,'description',e.target.value)} placeholder="e.g. Mixing bowls"/></label><button type="button" className="text-button" aria-label={'Remove item '+(i+1)} onClick={()=>changeItems(items.filter((_,index)=>index!==i))}>Remove</button></div>)}<button type="button" className="secondary" disabled={items.length>=22} onClick={()=>changeItems([...items,{quantity:'1',description:''}])}>+ Add item</button><small className="field-hint">{items.length} of 22 equipment rows used</small></fieldset><div className="booking-terms"><details><summary>Read the Terms and Conditions</summary><ol>{college.rules.map(rule=><li key={rule}>{rule}</li>)}</ol><p>Requests need laboratory office approval. Your instructor’s signed utilization form must be checked before approval.</p></details><label className="check-label"><input type="checkbox" name="termsAccepted" required checked={fields.termsAccepted} onChange={update}/><span>I have read and agree to the Terms and Conditions.</span></label></div><p className="signature-hint">After sending, your filled form downloads automatically. You can download it again in My bookings. For reference, view the blank <a href={college.labFormUrl} download>utilization form ↓</a> and arrange the required instructor signature on your filled copy.</p></div>}
 {problem&&<div className="alert" role="alert">{problem}</div>}<div className="guided-actions">{step>0&&<button className="secondary" type="button" disabled={busy} onClick={()=>{setStep(step-1);setProblem('')}}>← Back</button>}<span className="step-counter">Step {step+1} of 3</span><button className="primary" disabled={busy} type="submit">{busy?'Sending request…':step===2?'Send booking request ↗':'Continue →'}</button></div></form>
}
